### PR TITLE
add licenses to every file and add READMEs

### LINKED ISSUE #3: Unclear license
Tough some files have a license declaration in their header (GPL-2.0+), most don't have one. I recommend to clarify it with one file in the top directory.

Thanks!

### PR DESCRIPTION
**Pull request by davidak**
@sp-apertus added a LICENSE file for this repository, so we don't need it in every single file.

I removed it and put authors into README (Contributors). I preserved license from scripts from different sources (Magic Latern, ...).

@alexdu @sebix @irieger is it ok for you that we updated the license from GPLv2 or newer to GPLv3?

fixes #3

### CODE REVIEW

**Comment by sebix** [comment]
I recommend to follow the advises at https://reuse.software/
>
> @alexdu <https://github.com/alexdu> @sebix <https://github.com/sebix>
> is it ok for you that we updated the license from GPLv2 or newer to GPLv3?
>
Yes
>
-- 
python programming - mail server - photo - video - https://sebix.at
cryptographic key at https://sebix.at/DC9B463B.asc and on public keyservers

**Comment by davidak** [comment]
@sebix thanks for the link. we have 1. and 3. is not needed since we have only 2 files from Magic Latern.

We can discuss if we should add a license header to every single file (currently 77).

**Comment by sp-apertus** [comment]
license in every file header it is then

**Comment by davidak** [comment]
@alexdu sure is "GPLv2 or later" compatible with v3, but you might have reasons to stick with v2.

Like you see in the graphics in the thread you linked to, a v2 project would have to upgrade to v3 if they want to use v3 code. So the license is also viral inside it's own ecosystem :D

@sp-apertus great, i will do it (later)

**Comment by davidak** [comment]
I have added license headers to all files including `SPDX-License-Identifier`.

I was not able to reconstruct who initially wrote the `color-calibration` octave code. Was that you @alexdu?

Also i'm not sure if the octave code still works. I used "function headers" as described here: https://www.gnu.org/software/octave/doc/v4.0.0/Function-Headers.html

Please verify.

My text editor removed some whitespace at the end of the line. Hope that's OK.

**Comment by sebix** [comment]
> I have added license headers to all files including `SPDX-License-Identifier`.

Did you automate it or have you done that by hand?

**Comment by davidak** [comment]
@sebix i have done it by hand. some files need other comment syntax...

**Comment by sp-apertus** [comment]
Looks good, will merge when alex gives green light.

**Pull request merged**
